site_name: SQL & Java - Your getting started Guide
site_url: https://rainbowdashlabs.github.io/BasicSQLPlugin/
site_description: Your goto page when you start with java and sql.
repo_url: https://github.com/RainbowDashLabs/BasicSQLPlugin/
repo_name: Basic SQL Plugin
plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
#pages:
#- ['index.md', 'Welcome']
#- ['01/preface.md', 'Chapter 1 The basics', 'Preface']
#- ['01/introduction.md', 'Chapter 1 The basics', 'Introduction']
nav:
  - Home: index.md
  - 'Chapter 1 The basics':
    - 'Preface': 01/preface.md
    - 'Introduction': 01/introduction.md
theme:
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
#    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
  language: en
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
